### PR TITLE
CI

### PR DESCRIPTION
**Pull request by UlisesGascon**

### CODE REVIEW

**Comment by danielherrerohernando** [comment]
I´ve just added a **sleep 5** after the docker-compose up command to make sure that db container is running and ready to accept connections prior to running the test suite.

A cleaner solution is waiting for the container running state to be "true" instead of waiting a specific amount of seconds which in fact means wasting time in every build cause the machine is just sleeping. The snippet we use in our Disco pipelines looks like this:
`      until [ "`/usr/bin/docker inspect -f {{.State.Running}} CONTAINER_NAME`"=="true" ]; do
        echo "waiting for the container to be up"
        sleep 0.5;
      done;`

**Comment by UlisesGascon** [comment]
Awesome approach @danielherrerohernando! Maybe we can use [Docker wait](https://docs.docker.com/engine/reference/commandline/wait/)?

**Comment by danielherrerohernando** [comment]
> Awesome approach @danielherrerohernando! Maybe we can use [Docker wait](https://docs.docker.com/engine/reference/commandline/wait/)?

As far as I know from the docs with docker wait you can stop the script's execution until a specific container stops, which is not our case here (the db gets up and doesn't stop til the end of the build pipeline).

Our case is well explained here: https://docs.docker.com/compose/startup-order/ Here they show the difference between being up and being ready.

> However, for startup Compose does not wait until a container is “ready” (whatever that means for your particular application) - only until it’s running. There’s a good reason for this.

> 
That's why they recommend to use some kind of "wait for it" script when starting a container that depends on another one @UlisesGascon

**Comment by UlisesGascon** [comment]
Thanks for the analysis! I will merge it now

**Pull request merged**
