### PR TITLE
Node 14 compatible

### PR DESCRIPTION
**Pull request by inigomarquinez**
### Main changes

- chore: dependencies updated to the latest versions so we can use the library in node v14 environments

### Other changes

- chore: minor version upgraded
- chore: `.nvmrc` file updated

### CODE REVIEW

**Comment by neodmy** [comment]
Thanks @inigomarquinez. This is causing problems because the service won't boot up, and you get no errors (even using `debug` AFAIK)

**Review by neodmy — APPROVED** [review]
🥒

**Comment by Betisman** [comment]
Especially now that systemic is being bumped to Node 14

**Review by danielherrerohernando — APPROVED** [review]
🚀

**Review by kevinccbsg — APPROVED** [review]

**Pull request merged**
